### ISSUE TITLE
Error: Manifest version 2

### ISSUE THREAD

**Issue by slambo311** [felixtrz/WebXRQuestEmulator#2]
When I installed this on Chrome, I got this error:

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
![image](https://user-images.githubusercontent.com/61334045/198133237-3e548865-0fe9-416f-9439-952331e7bbea.png)

**Comment by felixtrz** [comment]
This should not affect the extension from working as expected. I am porting it to version 3 later this year
